DATASETS:
        FEATURE_TEST: (['features_database.pt', 'features_query.pt'])
        POSE_TEST: (['poses_database.pt', 'poses_query.pt'])
        MASK_TEST: (['masks_database.pt', 'masks_query.pt'])
        SCORE: 'adjacency_matrix_eval.pt'
        RUN_ID_TEST: (['subgraph_run_id_database.pt', 'subgraph_run_id_query.pt'])
        NODEINFO_TEST: (['subgraph_nodes_database.pt', 'subgraph_nodes_query.pt'])
MODEL:
        ATTENTION_GRAPH:
                POSE_DIM: 2
                FEATURE_DIM: 256
                NUM_HEADS: 4
                NUM_LAYERS: 9
                INCLUDE_POSE: True
                DROPOUT: 0.0
TEST:
        MODEL_PARAM: 'attentional_graph.pt'
        STRIDE: 1
DATA_DIR: ['data/model_train/oxford/d200/']
OUTPUT_DIR: './'
